name: Build and Zip

on:
  push:
    branches:
      - main

jobs:
  build-and-zip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.7.0
      
    - name: Zip repo
      run: zip -r my-repo.zip .
      
    - name: Upload zip artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: my-repo.zip
        path: my-repo.zip
